### ISSUE TITLE
How to run it on a Mac?

### ISSUE THREAD

**Issue by deemeetree** [Augmenta-tech/Augmenta-Simulator#1]

**Comment by Lyptik** [comment]
We will provide soon a mac build here. Meanwhile you can also buil it from source.

**Comment by deemeetree** [comment]
Ok, cool and how to do that?

**Comment by alexbourgeois** [comment]
Mac version 2.1.2 released, you can download it !

**Comment by deemeetree** [comment]
Ok, I install it, but when I try to use Node.Js software to receive OSC it doesn't detect anything: https://github.com/colinbdclark/osc.js/

**Comment by Lyptik** [comment]
Hello Dimitry,

It's standard osc so as long as you send data to correct target IP and target port to your server it should be fine.
You can still use any app osc receiving app like https://osculator.net/ for example to check that the simulator is sending correctly.
Then if it's fine you might have to check the parameters on your nodejs server.
We never tested it but somebody made a nodejs node and shared with the community, you might have a look at this and even contribute if you feel like it !
https://github.com/Theoriz/Augmenta-node
All the best,
