### ISSUE TITLE
linux release

### ISSUE THREAD

**Issue by dewiweb** [Augmenta-tech/Augmenta-Simulator#3]
Do you think possible to build a linux version of augmenta-simulator?

**Comment by alexbourgeois** [comment]
I did a pre-release for linux, I tested it on Ubuntu 16.04 and it seems to work, can you confirm on your system ?

**Comment by dewiweb** [comment]
Hello,
I'm on linuxmint 19.3 (based on ubuntu). when i launch the pre-release i just have a pink window like this:
![Capture du 2019-06-11 18-52-56](https://user-images.githubusercontent.com/3625655/59291461-3768ec80-8c7b-11e9-88ce-93fef3581949.png)

**Comment by alexbourgeois** [comment]
Hi, sorry for the delay. It is very strange and hard to reproduce on my side. Can you transfer me the log file located in : /home/dewi/.config/unity3d/Editor/Player.log ? It seems to be a graphical problem, driver maybe, what are the specs of your computer ?

**Comment by dewiweb** [comment]
Apparently, it's due to incompatibility between unity3d version and my gpu (intel graphics hd4000 ivybridge).
I'm now able to open simulator with this workaround (adding "-force-vulkan" to the commandline)

[https://askubuntu.com/questions/1144268/unity-3d-editor-window-filled-with-pink-color/1146337#1146337](url)

but the result is not really usable:
![Capture du 2019-06-26 18-34-14](https://user-images.githubusercontent.com/3625655/60198178-4df97100-9841-11e9-8c1a-e5015ec40650.png)

**Comment by alexbourgeois** [comment]
Ok interesting, I take note of this workaround, thank you. The issue remaining comes from the fonts we use (Century Gothic and Roboto). Unfortunately I can't reproduce this bug, can you make sure you have the Arial font installed on your computer ? Unity should fall back to this one if it can't load ours.

**Comment by dewiweb** [comment]
I've got all these fonts installed on my os but unity3d seems to not find its...

**Comment by alexbourgeois** [comment]
Strange .. Did you try to open the project itself in Unity ? If not it might be very interesting to give it a try, I wonder what would happen.
